version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nimbusdb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nimbusdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nimbusdb"]
      interval: 3s
      timeout: 3s
      retries: 5

  metadata-service:
    build:
      context: ../../services/metadata-service
      dockerfile: Dockerfile
    container_name: nimbusdb_metadata
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/nimbusdb?sslmode=disable
      PORT: 8080
      GRPC_PORT: 50051
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy

  scheduler:
    build:
      context: ../../services/scheduler
      dockerfile: Dockerfile
    container_name: nimbusdb_scheduler
    environment:
      METADATA_GRPC_ADDR: metadata-service:50051
      SCHEDULER_PORT: 50052
    ports:
      - "50052:50052"
    depends_on:
      - metadata-service

  worker-1:
    build:
      context: ../../services/worker-node
      dockerfile: Dockerfile
    container_name: nimbusdb_worker_1
    environment:
      METADATA_GRPC_ADDR: metadata-service:50051
      CLUSTER_ID: 00000000-0000-0000-0000-000000000000
      HOSTNAME: worker-1
      DEBUG_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - metadata-service

  worker-2:
    build:
      context: ../../services/worker-node
      dockerfile: Dockerfile
    container_name: nimbusdb_worker_2
    environment:
      METADATA_GRPC_ADDR: metadata-service:50051
      CLUSTER_ID: 00000000-0000-0000-0000-000000000000
      HOSTNAME: worker-2
      DEBUG_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - metadata-service

  worker-3:
    build:
      context: ../../services/worker-node
      dockerfile: Dockerfile
    container_name: nimbusdb_worker_3
    environment:
      METADATA_GRPC_ADDR: metadata-service:50051
      CLUSTER_ID: 00000000-0000-0000-0000-000000000000
      HOSTNAME: worker-3
      DEBUG_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      - metadata-service

volumes:
  pgdata:
