// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/operations.proto

package operations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartDeploymentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeploymentType     string                 `protobuf:"bytes,1,opt,name=deployment_type,json=deploymentType,proto3" json:"deployment_type,omitempty"` // "rolling", "canary", "blue-green"
	TargetVersion      string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	CanaryWeight       int32                  `protobuf:"varint,3,opt,name=canary_weight,json=canaryWeight,proto3" json:"canary_weight,omitempty"` // e.g. 10 for 10%
	ObservationSeconds int32                  `protobuf:"varint,4,opt,name=observation_seconds,json=observationSeconds,proto3" json:"observation_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartDeploymentRequest) Reset() {
	*x = StartDeploymentRequest{}
	mi := &file_proto_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeploymentRequest) ProtoMessage() {}

func (x *StartDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeploymentRequest.ProtoReflect.Descriptor instead.
func (*StartDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{0}
}

func (x *StartDeploymentRequest) GetDeploymentType() string {
	if x != nil {
		return x.DeploymentType
	}
	return ""
}

func (x *StartDeploymentRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *StartDeploymentRequest) GetCanaryWeight() int32 {
	if x != nil {
		return x.CanaryWeight
	}
	return 0
}

func (x *StartDeploymentRequest) GetObservationSeconds() int32 {
	if x != nil {
		return x.ObservationSeconds
	}
	return 0
}

type StartDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeploymentResponse) Reset() {
	*x = StartDeploymentResponse{}
	mi := &file_proto_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeploymentResponse) ProtoMessage() {}

func (x *StartDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeploymentResponse.ProtoReflect.Descriptor instead.
func (*StartDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{1}
}

func (x *StartDeploymentResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *StartDeploymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDeploymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_proto_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeploymentStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetDeploymentStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId   string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	DeploymentType string                 `protobuf:"bytes,2,opt,name=deployment_type,json=deploymentType,proto3" json:"deployment_type,omitempty"`
	TargetVersion  string                 `protobuf:"bytes,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "in_progress", "completed", "failed", "rolled_back"
	TrafficSplit   int32                  `protobuf:"varint,5,opt,name=traffic_split,json=trafficSplit,proto3" json:"traffic_split,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDeploymentStatusResponse) Reset() {
	*x = GetDeploymentStatusResponse{}
	mi := &file_proto_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResponse) ProtoMessage() {}

func (x *GetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeploymentStatusResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetDeploymentType() string {
	if x != nil {
		return x.DeploymentType
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetTrafficSplit() int32 {
	if x != nil {
		return x.TrafficSplit
	}
	return 0
}

func (x *GetDeploymentStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TriggerRollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRollbackRequest) Reset() {
	*x = TriggerRollbackRequest{}
	mi := &file_proto_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRollbackRequest) ProtoMessage() {}

func (x *TriggerRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRollbackRequest.ProtoReflect.Descriptor instead.
func (*TriggerRollbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerRollbackRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *TriggerRollbackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TriggerRollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRollbackResponse) Reset() {
	*x = TriggerRollbackResponse{}
	mi := &file_proto_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRollbackResponse) ProtoMessage() {}

func (x *TriggerRollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRollbackResponse.ProtoReflect.Descriptor instead.
func (*TriggerRollbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerRollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerRollbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_proto_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{6}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DrainNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DatabasesMoved int32                  `protobuf:"varint,2,opt,name=databases_moved,json=databasesMoved,proto3" json:"databases_moved,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_proto_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{7}
}

func (x *DrainNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DrainNodeResponse) GetDatabasesMoved() int32 {
	if x != nil {
		return x.DatabasesMoved
	}
	return 0
}

func (x *DrainNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PredictCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HorizonDays   int32                  `protobuf:"varint,1,opt,name=horizon_days,json=horizonDays,proto3" json:"horizon_days,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"` // "cpu", "memory", "rps"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictCapacityRequest) Reset() {
	*x = PredictCapacityRequest{}
	mi := &file_proto_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictCapacityRequest) ProtoMessage() {}

func (x *PredictCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictCapacityRequest.ProtoReflect.Descriptor instead.
func (*PredictCapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{8}
}

func (x *PredictCapacityRequest) GetHorizonDays() int32 {
	if x != nil {
		return x.HorizonDays
	}
	return 0
}

func (x *PredictCapacityRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type PredictCapacityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentNodes   int32                  `protobuf:"varint,1,opt,name=current_nodes,json=currentNodes,proto3" json:"current_nodes,omitempty"`
	ProjectedNodes int32                  `protobuf:"varint,2,opt,name=projected_nodes,json=projectedNodes,proto3" json:"projected_nodes,omitempty"`
	GrowthRatePct  float64                `protobuf:"fixed64,3,opt,name=growth_rate_pct,json=growthRatePct,proto3" json:"growth_rate_pct,omitempty"`
	Method         string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // "linear_regression", "moving_average"
	HorizonDate    string                 `protobuf:"bytes,5,opt,name=horizon_date,json=horizonDate,proto3" json:"horizon_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PredictCapacityResponse) Reset() {
	*x = PredictCapacityResponse{}
	mi := &file_proto_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictCapacityResponse) ProtoMessage() {}

func (x *PredictCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictCapacityResponse.ProtoReflect.Descriptor instead.
func (*PredictCapacityResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{9}
}

func (x *PredictCapacityResponse) GetCurrentNodes() int32 {
	if x != nil {
		return x.CurrentNodes
	}
	return 0
}

func (x *PredictCapacityResponse) GetProjectedNodes() int32 {
	if x != nil {
		return x.ProjectedNodes
	}
	return 0
}

func (x *PredictCapacityResponse) GetGrowthRatePct() float64 {
	if x != nil {
		return x.GrowthRatePct
	}
	return 0
}

func (x *PredictCapacityResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PredictCapacityResponse) GetHorizonDate() string {
	if x != nil {
		return x.HorizonDate
	}
	return ""
}

type RecordEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "request_success", "request_failure", "outage_start", "outage_resolved"
	LatencyMs     int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventRequest) Reset() {
	*x = RecordEventRequest{}
	mi := &file_proto_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventRequest) ProtoMessage() {}

func (x *RecordEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventRequest.ProtoReflect.Descriptor instead.
func (*RecordEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{10}
}

func (x *RecordEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordEventRequest) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RecordEventRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_proto_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{11}
}

func (x *RecordEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSLAReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowMinutes int32                  `protobuf:"varint,1,opt,name=window_minutes,json=windowMinutes,proto3" json:"window_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSLAReportRequest) Reset() {
	*x = GetSLAReportRequest{}
	mi := &file_proto_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSLAReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSLAReportRequest) ProtoMessage() {}

func (x *GetSLAReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSLAReportRequest.ProtoReflect.Descriptor instead.
func (*GetSLAReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{12}
}

func (x *GetSLAReportRequest) GetWindowMinutes() int32 {
	if x != nil {
		return x.WindowMinutes
	}
	return 0
}

type GetSLAReportResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AvailabilityPct float64                `protobuf:"fixed64,1,opt,name=availability_pct,json=availabilityPct,proto3" json:"availability_pct,omitempty"`
	P95LatencyMs    int64                  `protobuf:"varint,2,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs    int64                  `protobuf:"varint,3,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	TotalRequests   int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FailedRequests  int64                  `protobuf:"varint,5,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	MttrSeconds     int64                  `protobuf:"varint,6,opt,name=mttr_seconds,json=mttrSeconds,proto3" json:"mttr_seconds,omitempty"`
	SloMet          bool                   `protobuf:"varint,7,opt,name=slo_met,json=sloMet,proto3" json:"slo_met,omitempty"` // true if availability >= 99.9%
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSLAReportResponse) Reset() {
	*x = GetSLAReportResponse{}
	mi := &file_proto_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSLAReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSLAReportResponse) ProtoMessage() {}

func (x *GetSLAReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSLAReportResponse.ProtoReflect.Descriptor instead.
func (*GetSLAReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_operations_proto_rawDescGZIP(), []int{13}
}

func (x *GetSLAReportResponse) GetAvailabilityPct() float64 {
	if x != nil {
		return x.AvailabilityPct
	}
	return 0
}

func (x *GetSLAReportResponse) GetP95LatencyMs() int64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *GetSLAReportResponse) GetP99LatencyMs() int64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *GetSLAReportResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetSLAReportResponse) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *GetSLAReportResponse) GetMttrSeconds() int64 {
	if x != nil {
		return x.MttrSeconds
	}
	return 0
}

func (x *GetSLAReportResponse) GetSloMet() bool {
	if x != nil {
		return x.SloMet
	}
	return false
}

var File_proto_operations_proto protoreflect.FileDescriptor

const file_proto_operations_proto_rawDesc = "" +
	"\n" +
	"\x16proto/operations.proto\x12\n" +
	"operations\"\xbe\x01\n" +
	"\x16StartDeploymentRequest\x12'\n" +
	"\x0fdeployment_type\x18\x01 \x01(\tR\x0edeploymentType\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\x12#\n" +
	"\rcanary_weight\x18\x03 \x01(\x05R\fcanaryWeight\x12/\n" +
	"\x13observation_seconds\x18\x04 \x01(\x05R\x12observationSeconds\"V\n" +
	"\x17StartDeploymentResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"A\n" +
	"\x1aGetDeploymentStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"\xf4\x01\n" +
	"\x1bGetDeploymentStatusResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12'\n" +
	"\x0fdeployment_type\x18\x02 \x01(\tR\x0edeploymentType\x12%\n" +
	"\x0etarget_version\x18\x03 \x01(\tR\rtargetVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rtraffic_split\x18\x05 \x01(\x05R\ftrafficSplit\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"U\n" +
	"\x16TriggerRollbackRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x17TriggerRollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"l\n" +
	"\x11DrainNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdatabases_moved\x18\x02 \x01(\x05R\x0edatabasesMoved\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\x16PredictCapacityRequest\x12!\n" +
	"\fhorizon_days\x18\x01 \x01(\x05R\vhorizonDays\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\"\xca\x01\n" +
	"\x17PredictCapacityResponse\x12#\n" +
	"\rcurrent_nodes\x18\x01 \x01(\x05R\fcurrentNodes\x12'\n" +
	"\x0fprojected_nodes\x18\x02 \x01(\x05R\x0eprojectedNodes\x12&\n" +
	"\x0fgrowth_rate_pct\x18\x03 \x01(\x01R\rgrowthRatePct\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12!\n" +
	"\fhorizon_date\x18\x05 \x01(\tR\vhorizonDate\"l\n" +
	"\x12RecordEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\"/\n" +
	"\x13RecordEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x13GetSLAReportRequest\x12%\n" +
	"\x0ewindow_minutes\x18\x01 \x01(\x05R\rwindowMinutes\"\x99\x02\n" +
	"\x14GetSLAReportResponse\x12)\n" +
	"\x10availability_pct\x18\x01 \x01(\x01R\x0favailabilityPct\x12$\n" +
	"\x0ep95_latency_ms\x18\x02 \x01(\x03R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x03 \x01(\x03R\fp99LatencyMs\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0ffailed_requests\x18\x05 \x01(\x03R\x0efailedRequests\x12!\n" +
	"\fmttr_seconds\x18\x06 \x01(\x03R\vmttrSeconds\x12\x17\n" +
	"\aslo_met\x18\a \x01(\bR\x06sloMet2\x87\x03\n" +
	"\x1bDeploymentControllerService\x12Z\n" +
	"\x0fStartDeployment\x12\".operations.StartDeploymentRequest\x1a#.operations.StartDeploymentResponse\x12f\n" +
	"\x13GetDeploymentStatus\x12&.operations.GetDeploymentStatusRequest\x1a'.operations.GetDeploymentStatusResponse\x12Z\n" +
	"\x0fTriggerRollback\x12\".operations.TriggerRollbackRequest\x1a#.operations.TriggerRollbackResponse\x12H\n" +
	"\tDrainNode\x12\x1c.operations.DrainNodeRequest\x1a\x1d.operations.DrainNodeResponse2t\n" +
	"\x16CapacityPlannerService\x12Z\n" +
	"\x0fPredictCapacity\x12\".operations.PredictCapacityRequest\x1a#.operations.PredictCapacityResponse2\xb6\x01\n" +
	"\x11SLAMonitorService\x12N\n" +
	"\vRecordEvent\x12\x1e.operations.RecordEventRequest\x1a\x1f.operations.RecordEventResponse\x12Q\n" +
	"\fGetSLAReport\x12\x1f.operations.GetSLAReportRequest\x1a .operations.GetSLAReportResponseBOZMgithub.com/onlyarnav/nimbusdb/services/deployment-controller/proto;operationsb\x06proto3"

var (
	file_proto_operations_proto_rawDescOnce sync.Once
	file_proto_operations_proto_rawDescData []byte
)

func file_proto_operations_proto_rawDescGZIP() []byte {
	file_proto_operations_proto_rawDescOnce.Do(func() {
		file_proto_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_operations_proto_rawDesc), len(file_proto_operations_proto_rawDesc)))
	})
	return file_proto_operations_proto_rawDescData
}

var file_proto_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_operations_proto_goTypes = []any{
	(*StartDeploymentRequest)(nil),      // 0: operations.StartDeploymentRequest
	(*StartDeploymentResponse)(nil),     // 1: operations.StartDeploymentResponse
	(*GetDeploymentStatusRequest)(nil),  // 2: operations.GetDeploymentStatusRequest
	(*GetDeploymentStatusResponse)(nil), // 3: operations.GetDeploymentStatusResponse
	(*TriggerRollbackRequest)(nil),      // 4: operations.TriggerRollbackRequest
	(*TriggerRollbackResponse)(nil),     // 5: operations.TriggerRollbackResponse
	(*DrainNodeRequest)(nil),            // 6: operations.DrainNodeRequest
	(*DrainNodeResponse)(nil),           // 7: operations.DrainNodeResponse
	(*PredictCapacityRequest)(nil),      // 8: operations.PredictCapacityRequest
	(*PredictCapacityResponse)(nil),     // 9: operations.PredictCapacityResponse
	(*RecordEventRequest)(nil),          // 10: operations.RecordEventRequest
	(*RecordEventResponse)(nil),         // 11: operations.RecordEventResponse
	(*GetSLAReportRequest)(nil),         // 12: operations.GetSLAReportRequest
	(*GetSLAReportResponse)(nil),        // 13: operations.GetSLAReportResponse
}
var file_proto_operations_proto_depIdxs = []int32{
	0,  // 0: operations.DeploymentControllerService.StartDeployment:input_type -> operations.StartDeploymentRequest
	2,  // 1: operations.DeploymentControllerService.GetDeploymentStatus:input_type -> operations.GetDeploymentStatusRequest
	4,  // 2: operations.DeploymentControllerService.TriggerRollback:input_type -> operations.TriggerRollbackRequest
	6,  // 3: operations.DeploymentControllerService.DrainNode:input_type -> operations.DrainNodeRequest
	8,  // 4: operations.CapacityPlannerService.PredictCapacity:input_type -> operations.PredictCapacityRequest
	10, // 5: operations.SLAMonitorService.RecordEvent:input_type -> operations.RecordEventRequest
	12, // 6: operations.SLAMonitorService.GetSLAReport:input_type -> operations.GetSLAReportRequest
	1,  // 7: operations.DeploymentControllerService.StartDeployment:output_type -> operations.StartDeploymentResponse
	3,  // 8: operations.DeploymentControllerService.GetDeploymentStatus:output_type -> operations.GetDeploymentStatusResponse
	5,  // 9: operations.DeploymentControllerService.TriggerRollback:output_type -> operations.TriggerRollbackResponse
	7,  // 10: operations.DeploymentControllerService.DrainNode:output_type -> operations.DrainNodeResponse
	9,  // 11: operations.CapacityPlannerService.PredictCapacity:output_type -> operations.PredictCapacityResponse
	11, // 12: operations.SLAMonitorService.RecordEvent:output_type -> operations.RecordEventResponse
	13, // 13: operations.SLAMonitorService.GetSLAReport:output_type -> operations.GetSLAReportResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_operations_proto_init() }
func file_proto_operations_proto_init() {
	if File_proto_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_operations_proto_rawDesc), len(file_proto_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_operations_proto_goTypes,
		DependencyIndexes: file_proto_operations_proto_depIdxs,
		MessageInfos:      file_proto_operations_proto_msgTypes,
	}.Build()
	File_proto_operations_proto = out.File
	file_proto_operations_proto_goTypes = nil
	file_proto_operations_proto_depIdxs = nil
}
