apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nimbusdb.fullname" . }}-config
  labels:
    {{- include "nimbusdb.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  PORT: {{ .Values.gateway.httpPort | quote }}
  METADATA_PORT: {{ .Values.metadataService.httpPort | quote }}
  METADATA_GRPC_PORT: {{ .Values.metadataService.grpcPort | quote }}
  SCHEDULER_PORT: {{ .Values.scheduler.grpcPort | quote }}
  NODE_AGENT_PORT: {{ .Values.workerNode.grpcPort | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nimbusdb.fullname" . }}-secrets
  labels:
    {{- include "nimbusdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  DATABASE_URL: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "nimbusdb.fullname" . }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}?sslmode=disable"
