// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: metadata_service.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_metadata_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterNodeResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NodeId                   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_metadata_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type SendHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPct        float32                `protobuf:"fixed32,2,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemoryPct     float32                `protobuf:"fixed32,3,opt,name=memory_pct,json=memoryPct,proto3" json:"memory_pct,omitempty"`
	DiskPct       float32                `protobuf:"fixed32,4,opt,name=disk_pct,json=diskPct,proto3" json:"disk_pct,omitempty"`
	Healthy       bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatRequest) Reset() {
	*x = SendHeartbeatRequest{}
	mi := &file_metadata_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatRequest) ProtoMessage() {}

func (x *SendHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SendHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SendHeartbeatRequest) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *SendHeartbeatRequest) GetMemoryPct() float32 {
	if x != nil {
		return x.MemoryPct
	}
	return 0
}

func (x *SendHeartbeatRequest) GetDiskPct() float32 {
	if x != nil {
		return x.DiskPct
	}
	return 0
}

func (x *SendHeartbeatRequest) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type SendHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHeartbeatResponse) Reset() {
	*x = SendHeartbeatResponse{}
	mi := &file_metadata_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHeartbeatResponse) ProtoMessage() {}

func (x *SendHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*SendHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_metadata_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CpuPct        float32                `protobuf:"fixed32,5,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemoryPct     float32                `protobuf:"fixed32,6,opt,name=memory_pct,json=memoryPct,proto3" json:"memory_pct,omitempty"`
	DiskPct       float32                `protobuf:"fixed32,7,opt,name=disk_pct,json=diskPct,proto3" json:"disk_pct,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // RFC3339 string
	RegisteredAt  string                 `protobuf:"bytes,9,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`    // RFC3339 string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_metadata_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *NodeInfo) GetMemoryPct() float32 {
	if x != nil {
		return x.MemoryPct
	}
	return 0
}

func (x *NodeInfo) GetDiskPct() float32 {
	if x != nil {
		return x.DiskPct
	}
	return 0
}

func (x *NodeInfo) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *NodeInfo) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_metadata_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_metadata_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ScheduleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Score          float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	ScoreBreakdown map[string]float32     `protobuf:"bytes,3,rep,name=score_breakdown,json=scoreBreakdown,proto3" json:"score_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_metadata_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ScheduleResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScheduleResponse) GetScoreBreakdown() map[string]float32 {
	if x != nil {
		return x.ScoreBreakdown
	}
	return nil
}

type CreateDatabaseRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRecordRequest) Reset() {
	*x = CreateDatabaseRecordRequest{}
	mi := &file_metadata_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRecordRequest) ProtoMessage() {}

func (x *CreateDatabaseRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRecordRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDatabaseRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseRecordRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CreateDatabaseRecordRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateDatabaseRecordRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateDatabaseRecordRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type CreateDatabaseRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRecordResponse) Reset() {
	*x = CreateDatabaseRecordResponse{}
	mi := &file_metadata_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRecordResponse) ProtoMessage() {}

func (x *CreateDatabaseRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRecordResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDatabaseRecordResponse) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type UpdateDatabaseStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Attempts      int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseStatusRequest) Reset() {
	*x = UpdateDatabaseStatusRequest{}
	mi := &file_metadata_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseStatusRequest) ProtoMessage() {}

func (x *UpdateDatabaseStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseStatusRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDatabaseStatusRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *UpdateDatabaseStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDatabaseStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateDatabaseStatusRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *UpdateDatabaseStatusRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type UpdateDatabaseStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatabaseStatusResponse) Reset() {
	*x = UpdateDatabaseStatusResponse{}
	mi := &file_metadata_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatabaseStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatabaseStatusResponse) ProtoMessage() {}

func (x *UpdateDatabaseStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatabaseStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatabaseStatusResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDatabaseStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_metadata_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type DatabaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_metadata_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{14}
}

func (x *DatabaseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatabaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatabaseInfo) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DatabaseInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DatabaseInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DatabaseInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DatabaseInfo) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DatabaseInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DatabaseInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DatabaseInfo          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_metadata_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetDatabaseResponse) GetDatabase() *DatabaseInfo {
	if x != nil {
		return x.Database
	}
	return nil
}

type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_metadata_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListDatabasesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*DatabaseInfo        `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_metadata_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListDatabasesResponse) GetDatabases() []*DatabaseInfo {
	if x != nil {
		return x.Databases
	}
	return nil
}

type DeleteDatabaseRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRecordRequest) Reset() {
	*x = DeleteDatabaseRecordRequest{}
	mi := &file_metadata_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRecordRequest) ProtoMessage() {}

func (x *DeleteDatabaseRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRecordRequest) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDatabaseRecordRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type DeleteDatabaseRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRecordResponse) Reset() {
	*x = DeleteDatabaseRecordResponse{}
	mi := &file_metadata_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRecordResponse) ProtoMessage() {}

func (x *DeleteDatabaseRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRecordResponse) Descriptor() ([]byte, []int) {
	return file_metadata_service_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDatabaseRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_metadata_service_proto protoreflect.FileDescriptor

const file_metadata_service_proto_rawDesc = "" +
	"\n" +
	"\x16metadata_service.proto\x12\bmetadata\"P\n" +
	"\x13RegisterNodeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"m\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\"\x9c\x01\n" +
	"\x14SendHeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\acpu_pct\x18\x02 \x01(\x02R\x06cpuPct\x12\x1d\n" +
	"\n" +
	"memory_pct\x18\x03 \x01(\x02R\tmemoryPct\x12\x19\n" +
	"\bdisk_pct\x18\x04 \x01(\x02R\adiskPct\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\"1\n" +
	"\x15SendHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x0fGetNodesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\x8c\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\acpu_pct\x18\x05 \x01(\x02R\x06cpuPct\x12\x1d\n" +
	"\n" +
	"memory_pct\x18\x06 \x01(\x02R\tmemoryPct\x12\x19\n" +
	"\bdisk_pct\x18\a \x01(\x02R\adiskPct\x12%\n" +
	"\x0elast_heartbeat\x18\b \x01(\tR\rlastHeartbeat\x12#\n" +
	"\rregistered_at\x18\t \x01(\tR\fregisteredAt\"<\n" +
	"\x10GetNodesResponse\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.metadata.NodeInfoR\x05nodes\"0\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\xdd\x01\n" +
	"\x10ScheduleResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12W\n" +
	"\x0fscore_breakdown\x18\x03 \x03(\v2..metadata.ScheduleResponse.ScoreBreakdownEntryR\x0escoreBreakdown\x1aA\n" +
	"\x13ScoreBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x9d\x01\n" +
	"\x1bCreateDatabaseRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\"?\n" +
	"\x1cCreateDatabaseRecordResponse\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"\xa7\x01\n" +
	"\x1bUpdateDatabaseStatusRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\"8\n" +
	"\x1cUpdateDatabaseStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x12GetDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"\xf8\x01\n" +
	"\fDatabaseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"I\n" +
	"\x13GetDatabaseResponse\x122\n" +
	"\bdatabase\x18\x01 \x01(\v2\x16.metadata.DatabaseInfoR\bdatabase\"5\n" +
	"\x14ListDatabasesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"M\n" +
	"\x15ListDatabasesResponse\x124\n" +
	"\tdatabases\x18\x01 \x03(\v2\x16.metadata.DatabaseInfoR\tdatabases\">\n" +
	"\x1bDeleteDatabaseRecordRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"8\n" +
	"\x1cDeleteDatabaseRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc8\x05\n" +
	"\x0fMetadataService\x12M\n" +
	"\fRegisterNode\x12\x1d.metadata.RegisterNodeRequest\x1a\x1e.metadata.RegisterNodeResponse\x12P\n" +
	"\rSendHeartbeat\x12\x1e.metadata.SendHeartbeatRequest\x1a\x1f.metadata.SendHeartbeatResponse\x12A\n" +
	"\bGetNodes\x12\x19.metadata.GetNodesRequest\x1a\x1a.metadata.GetNodesResponse\x12e\n" +
	"\x14CreateDatabaseRecord\x12%.metadata.CreateDatabaseRecordRequest\x1a&.metadata.CreateDatabaseRecordResponse\x12e\n" +
	"\x14UpdateDatabaseStatus\x12%.metadata.UpdateDatabaseStatusRequest\x1a&.metadata.UpdateDatabaseStatusResponse\x12J\n" +
	"\vGetDatabase\x12\x1c.metadata.GetDatabaseRequest\x1a\x1d.metadata.GetDatabaseResponse\x12P\n" +
	"\rListDatabases\x12\x1e.metadata.ListDatabasesRequest\x1a\x1f.metadata.ListDatabasesResponse\x12e\n" +
	"\x14DeleteDatabaseRecord\x12%.metadata.DeleteDatabaseRecordRequest\x1a&.metadata.DeleteDatabaseRecordResponse2U\n" +
	"\x10SchedulerService\x12A\n" +
	"\bSchedule\x12\x19.metadata.ScheduleRequest\x1a\x1a.metadata.ScheduleResponseBHZFgithub.com/onlyarnav/nimbusdb/services/metadata-service/proto;metadatab\x06proto3"

var (
	file_metadata_service_proto_rawDescOnce sync.Once
	file_metadata_service_proto_rawDescData []byte
)

func file_metadata_service_proto_rawDescGZIP() []byte {
	file_metadata_service_proto_rawDescOnce.Do(func() {
		file_metadata_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_service_proto_rawDesc), len(file_metadata_service_proto_rawDesc)))
	})
	return file_metadata_service_proto_rawDescData
}

var file_metadata_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_metadata_service_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),          // 0: metadata.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),         // 1: metadata.RegisterNodeResponse
	(*SendHeartbeatRequest)(nil),         // 2: metadata.SendHeartbeatRequest
	(*SendHeartbeatResponse)(nil),        // 3: metadata.SendHeartbeatResponse
	(*GetNodesRequest)(nil),              // 4: metadata.GetNodesRequest
	(*NodeInfo)(nil),                     // 5: metadata.NodeInfo
	(*GetNodesResponse)(nil),             // 6: metadata.GetNodesResponse
	(*ScheduleRequest)(nil),              // 7: metadata.ScheduleRequest
	(*ScheduleResponse)(nil),             // 8: metadata.ScheduleResponse
	(*CreateDatabaseRecordRequest)(nil),  // 9: metadata.CreateDatabaseRecordRequest
	(*CreateDatabaseRecordResponse)(nil), // 10: metadata.CreateDatabaseRecordResponse
	(*UpdateDatabaseStatusRequest)(nil),  // 11: metadata.UpdateDatabaseStatusRequest
	(*UpdateDatabaseStatusResponse)(nil), // 12: metadata.UpdateDatabaseStatusResponse
	(*GetDatabaseRequest)(nil),           // 13: metadata.GetDatabaseRequest
	(*DatabaseInfo)(nil),                 // 14: metadata.DatabaseInfo
	(*GetDatabaseResponse)(nil),          // 15: metadata.GetDatabaseResponse
	(*ListDatabasesRequest)(nil),         // 16: metadata.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),        // 17: metadata.ListDatabasesResponse
	(*DeleteDatabaseRecordRequest)(nil),  // 18: metadata.DeleteDatabaseRecordRequest
	(*DeleteDatabaseRecordResponse)(nil), // 19: metadata.DeleteDatabaseRecordResponse
	nil,                                  // 20: metadata.ScheduleResponse.ScoreBreakdownEntry
}
var file_metadata_service_proto_depIdxs = []int32{
	5,  // 0: metadata.GetNodesResponse.nodes:type_name -> metadata.NodeInfo
	20, // 1: metadata.ScheduleResponse.score_breakdown:type_name -> metadata.ScheduleResponse.ScoreBreakdownEntry
	14, // 2: metadata.GetDatabaseResponse.database:type_name -> metadata.DatabaseInfo
	14, // 3: metadata.ListDatabasesResponse.databases:type_name -> metadata.DatabaseInfo
	0,  // 4: metadata.MetadataService.RegisterNode:input_type -> metadata.RegisterNodeRequest
	2,  // 5: metadata.MetadataService.SendHeartbeat:input_type -> metadata.SendHeartbeatRequest
	4,  // 6: metadata.MetadataService.GetNodes:input_type -> metadata.GetNodesRequest
	9,  // 7: metadata.MetadataService.CreateDatabaseRecord:input_type -> metadata.CreateDatabaseRecordRequest
	11, // 8: metadata.MetadataService.UpdateDatabaseStatus:input_type -> metadata.UpdateDatabaseStatusRequest
	13, // 9: metadata.MetadataService.GetDatabase:input_type -> metadata.GetDatabaseRequest
	16, // 10: metadata.MetadataService.ListDatabases:input_type -> metadata.ListDatabasesRequest
	18, // 11: metadata.MetadataService.DeleteDatabaseRecord:input_type -> metadata.DeleteDatabaseRecordRequest
	7,  // 12: metadata.SchedulerService.Schedule:input_type -> metadata.ScheduleRequest
	1,  // 13: metadata.MetadataService.RegisterNode:output_type -> metadata.RegisterNodeResponse
	3,  // 14: metadata.MetadataService.SendHeartbeat:output_type -> metadata.SendHeartbeatResponse
	6,  // 15: metadata.MetadataService.GetNodes:output_type -> metadata.GetNodesResponse
	10, // 16: metadata.MetadataService.CreateDatabaseRecord:output_type -> metadata.CreateDatabaseRecordResponse
	12, // 17: metadata.MetadataService.UpdateDatabaseStatus:output_type -> metadata.UpdateDatabaseStatusResponse
	15, // 18: metadata.MetadataService.GetDatabase:output_type -> metadata.GetDatabaseResponse
	17, // 19: metadata.MetadataService.ListDatabases:output_type -> metadata.ListDatabasesResponse
	19, // 20: metadata.MetadataService.DeleteDatabaseRecord:output_type -> metadata.DeleteDatabaseRecordResponse
	8,  // 21: metadata.SchedulerService.Schedule:output_type -> metadata.ScheduleResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_metadata_service_proto_init() }
func file_metadata_service_proto_init() {
	if File_metadata_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_service_proto_rawDesc), len(file_metadata_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metadata_service_proto_goTypes,
		DependencyIndexes: file_metadata_service_proto_depIdxs,
		MessageInfos:      file_metadata_service_proto_msgTypes,
	}.Build()
	File_metadata_service_proto = out.File
	file_metadata_service_proto_goTypes = nil
	file_metadata_service_proto_depIdxs = nil
}
