// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: node_agent.proto

package nodeagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDatabaseResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CreateDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseRequest) Reset() {
	*x = DeleteDatabaseRequest{}
	mi := &file_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseRequest) ProtoMessage() {}

func (x *DeleteDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type DeleteDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatabaseResponse) Reset() {
	*x = DeleteDatabaseResponse{}
	mi := &file_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatabaseResponse) ProtoMessage() {}

func (x *DeleteDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BackupDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupDatabaseRequest) Reset() {
	*x = BackupDatabaseRequest{}
	mi := &file_node_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseRequest) ProtoMessage() {}

func (x *BackupDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseRequest.ProtoReflect.Descriptor instead.
func (*BackupDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{4}
}

func (x *BackupDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type BackupDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BackupPath    string                 `protobuf:"bytes,2,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupDatabaseResponse) Reset() {
	*x = BackupDatabaseResponse{}
	mi := &file_node_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseResponse) ProtoMessage() {}

func (x *BackupDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseResponse.ProtoReflect.Descriptor instead.
func (*BackupDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{5}
}

func (x *BackupDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupDatabaseResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *BackupDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RestoreDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	BackupPath    string                 `protobuf:"bytes,2,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreDatabaseRequest) Reset() {
	*x = RestoreDatabaseRequest{}
	mi := &file_node_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDatabaseRequest) ProtoMessage() {}

func (x *RestoreDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDatabaseRequest.ProtoReflect.Descriptor instead.
func (*RestoreDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *RestoreDatabaseRequest) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

type RestoreDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreDatabaseResponse) Reset() {
	*x = RestoreDatabaseResponse{}
	mi := &file_node_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDatabaseResponse) ProtoMessage() {}

func (x *RestoreDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDatabaseResponse.ProtoReflect.Descriptor instead.
func (*RestoreDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreDatabaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_node_agent_proto protoreflect.FileDescriptor

const file_node_agent_proto_rawDesc = "" +
	"\n" +
	"\x10node_agent.proto\x12\tnodeagent\"L\n" +
	"\x15CreateDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\"d\n" +
	"\x16CreateDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x15DeleteDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"H\n" +
	"\x16DeleteDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x15BackupDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"i\n" +
	"\x16BackupDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vbackup_path\x18\x02 \x01(\tR\n" +
	"backupPath\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Z\n" +
	"\x16RestoreDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x1f\n" +
	"\vbackup_path\x18\x02 \x01(\tR\n" +
	"backupPath\"I\n" +
	"\x17RestoreDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xea\x02\n" +
	"\tNodeAgent\x12U\n" +
	"\x0eCreateDatabase\x12 .nodeagent.CreateDatabaseRequest\x1a!.nodeagent.CreateDatabaseResponse\x12U\n" +
	"\x0eDeleteDatabase\x12 .nodeagent.DeleteDatabaseRequest\x1a!.nodeagent.DeleteDatabaseResponse\x12U\n" +
	"\x0eBackupDatabase\x12 .nodeagent.BackupDatabaseRequest\x1a!.nodeagent.BackupDatabaseResponse\x12X\n" +
	"\x0fRestoreDatabase\x12!.nodeagent.RestoreDatabaseRequest\x1a\".nodeagent.RestoreDatabaseResponseBDZBgithub.com/onlyarnav/nimbusdb/services/worker-node/proto;nodeagentb\x06proto3"

var (
	file_node_agent_proto_rawDescOnce sync.Once
	file_node_agent_proto_rawDescData []byte
)

func file_node_agent_proto_rawDescGZIP() []byte {
	file_node_agent_proto_rawDescOnce.Do(func() {
		file_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)))
	})
	return file_node_agent_proto_rawDescData
}

var file_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_node_agent_proto_goTypes = []any{
	(*CreateDatabaseRequest)(nil),   // 0: nodeagent.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),  // 1: nodeagent.CreateDatabaseResponse
	(*DeleteDatabaseRequest)(nil),   // 2: nodeagent.DeleteDatabaseRequest
	(*DeleteDatabaseResponse)(nil),  // 3: nodeagent.DeleteDatabaseResponse
	(*BackupDatabaseRequest)(nil),   // 4: nodeagent.BackupDatabaseRequest
	(*BackupDatabaseResponse)(nil),  // 5: nodeagent.BackupDatabaseResponse
	(*RestoreDatabaseRequest)(nil),  // 6: nodeagent.RestoreDatabaseRequest
	(*RestoreDatabaseResponse)(nil), // 7: nodeagent.RestoreDatabaseResponse
}
var file_node_agent_proto_depIdxs = []int32{
	0, // 0: nodeagent.NodeAgent.CreateDatabase:input_type -> nodeagent.CreateDatabaseRequest
	2, // 1: nodeagent.NodeAgent.DeleteDatabase:input_type -> nodeagent.DeleteDatabaseRequest
	4, // 2: nodeagent.NodeAgent.BackupDatabase:input_type -> nodeagent.BackupDatabaseRequest
	6, // 3: nodeagent.NodeAgent.RestoreDatabase:input_type -> nodeagent.RestoreDatabaseRequest
	1, // 4: nodeagent.NodeAgent.CreateDatabase:output_type -> nodeagent.CreateDatabaseResponse
	3, // 5: nodeagent.NodeAgent.DeleteDatabase:output_type -> nodeagent.DeleteDatabaseResponse
	5, // 6: nodeagent.NodeAgent.BackupDatabase:output_type -> nodeagent.BackupDatabaseResponse
	7, // 7: nodeagent.NodeAgent.RestoreDatabase:output_type -> nodeagent.RestoreDatabaseResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_agent_proto_init() }
func file_node_agent_proto_init() {
	if File_node_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_agent_proto_goTypes,
		DependencyIndexes: file_node_agent_proto_depIdxs,
		MessageInfos:      file_node_agent_proto_msgTypes,
	}.Build()
	File_node_agent_proto = out.File
	file_node_agent_proto_goTypes = nil
	file_node_agent_proto_depIdxs = nil
}
