// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/operations.proto

package operations

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentControllerService_StartDeployment_FullMethodName     = "/operations.DeploymentControllerService/StartDeployment"
	DeploymentControllerService_GetDeploymentStatus_FullMethodName = "/operations.DeploymentControllerService/GetDeploymentStatus"
	DeploymentControllerService_TriggerRollback_FullMethodName     = "/operations.DeploymentControllerService/TriggerRollback"
	DeploymentControllerService_DrainNode_FullMethodName           = "/operations.DeploymentControllerService/DrainNode"
)

// DeploymentControllerServiceClient is the client API for DeploymentControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeploymentController orchestrates rolling, canary, and blue-green deployments with auto-rollback.
type DeploymentControllerServiceClient interface {
	StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (*StartDeploymentResponse, error)
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	TriggerRollback(ctx context.Context, in *TriggerRollbackRequest, opts ...grpc.CallOption) (*TriggerRollbackResponse, error)
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
}

type deploymentControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentControllerServiceClient(cc grpc.ClientConnInterface) DeploymentControllerServiceClient {
	return &deploymentControllerServiceClient{cc}
}

func (c *deploymentControllerServiceClient) StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (*StartDeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDeploymentResponse)
	err := c.cc.Invoke(ctx, DeploymentControllerService_StartDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentControllerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, DeploymentControllerService_GetDeploymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentControllerServiceClient) TriggerRollback(ctx context.Context, in *TriggerRollbackRequest, opts ...grpc.CallOption) (*TriggerRollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRollbackResponse)
	err := c.cc.Invoke(ctx, DeploymentControllerService_TriggerRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentControllerServiceClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, DeploymentControllerService_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentControllerServiceServer is the server API for DeploymentControllerService service.
// All implementations must embed UnimplementedDeploymentControllerServiceServer
// for forward compatibility.
//
// DeploymentController orchestrates rolling, canary, and blue-green deployments with auto-rollback.
type DeploymentControllerServiceServer interface {
	StartDeployment(context.Context, *StartDeploymentRequest) (*StartDeploymentResponse, error)
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	TriggerRollback(context.Context, *TriggerRollbackRequest) (*TriggerRollbackResponse, error)
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	mustEmbedUnimplementedDeploymentControllerServiceServer()
}

// UnimplementedDeploymentControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentControllerServiceServer struct{}

func (UnimplementedDeploymentControllerServiceServer) StartDeployment(context.Context, *StartDeploymentRequest) (*StartDeploymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDeployment not implemented")
}
func (UnimplementedDeploymentControllerServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (UnimplementedDeploymentControllerServiceServer) TriggerRollback(context.Context, *TriggerRollbackRequest) (*TriggerRollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRollback not implemented")
}
func (UnimplementedDeploymentControllerServiceServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedDeploymentControllerServiceServer) mustEmbedUnimplementedDeploymentControllerServiceServer() {
}
func (UnimplementedDeploymentControllerServiceServer) testEmbeddedByValue() {}

// UnsafeDeploymentControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentControllerServiceServer will
// result in compilation errors.
type UnsafeDeploymentControllerServiceServer interface {
	mustEmbedUnimplementedDeploymentControllerServiceServer()
}

func RegisterDeploymentControllerServiceServer(s grpc.ServiceRegistrar, srv DeploymentControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedDeploymentControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentControllerService_ServiceDesc, srv)
}

func _DeploymentControllerService_StartDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentControllerServiceServer).StartDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentControllerService_StartDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentControllerServiceServer).StartDeployment(ctx, req.(*StartDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentControllerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentControllerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentControllerService_GetDeploymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentControllerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentControllerService_TriggerRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentControllerServiceServer).TriggerRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentControllerService_TriggerRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentControllerServiceServer).TriggerRollback(ctx, req.(*TriggerRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeploymentControllerService_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentControllerServiceServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploymentControllerService_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentControllerServiceServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploymentControllerService_ServiceDesc is the grpc.ServiceDesc for DeploymentControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.DeploymentControllerService",
	HandlerType: (*DeploymentControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDeployment",
			Handler:    _DeploymentControllerService_StartDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _DeploymentControllerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "TriggerRollback",
			Handler:    _DeploymentControllerService_TriggerRollback_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _DeploymentControllerService_DrainNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operations.proto",
}

const (
	CapacityPlannerService_PredictCapacity_FullMethodName = "/operations.CapacityPlannerService/PredictCapacity"
)

// CapacityPlannerServiceClient is the client API for CapacityPlannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapacityPlanner predicts cluster node needs based on historical load metrics.
type CapacityPlannerServiceClient interface {
	PredictCapacity(ctx context.Context, in *PredictCapacityRequest, opts ...grpc.CallOption) (*PredictCapacityResponse, error)
}

type capacityPlannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityPlannerServiceClient(cc grpc.ClientConnInterface) CapacityPlannerServiceClient {
	return &capacityPlannerServiceClient{cc}
}

func (c *capacityPlannerServiceClient) PredictCapacity(ctx context.Context, in *PredictCapacityRequest, opts ...grpc.CallOption) (*PredictCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictCapacityResponse)
	err := c.cc.Invoke(ctx, CapacityPlannerService_PredictCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityPlannerServiceServer is the server API for CapacityPlannerService service.
// All implementations must embed UnimplementedCapacityPlannerServiceServer
// for forward compatibility.
//
// CapacityPlanner predicts cluster node needs based on historical load metrics.
type CapacityPlannerServiceServer interface {
	PredictCapacity(context.Context, *PredictCapacityRequest) (*PredictCapacityResponse, error)
	mustEmbedUnimplementedCapacityPlannerServiceServer()
}

// UnimplementedCapacityPlannerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityPlannerServiceServer struct{}

func (UnimplementedCapacityPlannerServiceServer) PredictCapacity(context.Context, *PredictCapacityRequest) (*PredictCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictCapacity not implemented")
}
func (UnimplementedCapacityPlannerServiceServer) mustEmbedUnimplementedCapacityPlannerServiceServer() {
}
func (UnimplementedCapacityPlannerServiceServer) testEmbeddedByValue() {}

// UnsafeCapacityPlannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityPlannerServiceServer will
// result in compilation errors.
type UnsafeCapacityPlannerServiceServer interface {
	mustEmbedUnimplementedCapacityPlannerServiceServer()
}

func RegisterCapacityPlannerServiceServer(s grpc.ServiceRegistrar, srv CapacityPlannerServiceServer) {
	// If the following call panics, it indicates UnimplementedCapacityPlannerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapacityPlannerService_ServiceDesc, srv)
}

func _CapacityPlannerService_PredictCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityPlannerServiceServer).PredictCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityPlannerService_PredictCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityPlannerServiceServer).PredictCapacity(ctx, req.(*PredictCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityPlannerService_ServiceDesc is the grpc.ServiceDesc for CapacityPlannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityPlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.CapacityPlannerService",
	HandlerType: (*CapacityPlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictCapacity",
			Handler:    _CapacityPlannerService_PredictCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operations.proto",
}

const (
	SLAMonitorService_RecordEvent_FullMethodName  = "/operations.SLAMonitorService/RecordEvent"
	SLAMonitorService_GetSLAReport_FullMethodName = "/operations.SLAMonitorService/GetSLAReport"
)

// SLAMonitorServiceClient is the client API for SLAMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SLAMonitor tracks availability %, latency percentiles, and MTTR against an SLO.
type SLAMonitorServiceClient interface {
	RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error)
	GetSLAReport(ctx context.Context, in *GetSLAReportRequest, opts ...grpc.CallOption) (*GetSLAReportResponse, error)
}

type sLAMonitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSLAMonitorServiceClient(cc grpc.ClientConnInterface) SLAMonitorServiceClient {
	return &sLAMonitorServiceClient{cc}
}

func (c *sLAMonitorServiceClient) RecordEvent(ctx context.Context, in *RecordEventRequest, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, SLAMonitorService_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sLAMonitorServiceClient) GetSLAReport(ctx context.Context, in *GetSLAReportRequest, opts ...grpc.CallOption) (*GetSLAReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSLAReportResponse)
	err := c.cc.Invoke(ctx, SLAMonitorService_GetSLAReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SLAMonitorServiceServer is the server API for SLAMonitorService service.
// All implementations must embed UnimplementedSLAMonitorServiceServer
// for forward compatibility.
//
// SLAMonitor tracks availability %, latency percentiles, and MTTR against an SLO.
type SLAMonitorServiceServer interface {
	RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error)
	GetSLAReport(context.Context, *GetSLAReportRequest) (*GetSLAReportResponse, error)
	mustEmbedUnimplementedSLAMonitorServiceServer()
}

// UnimplementedSLAMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSLAMonitorServiceServer struct{}

func (UnimplementedSLAMonitorServiceServer) RecordEvent(context.Context, *RecordEventRequest) (*RecordEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedSLAMonitorServiceServer) GetSLAReport(context.Context, *GetSLAReportRequest) (*GetSLAReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSLAReport not implemented")
}
func (UnimplementedSLAMonitorServiceServer) mustEmbedUnimplementedSLAMonitorServiceServer() {}
func (UnimplementedSLAMonitorServiceServer) testEmbeddedByValue()                           {}

// UnsafeSLAMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SLAMonitorServiceServer will
// result in compilation errors.
type UnsafeSLAMonitorServiceServer interface {
	mustEmbedUnimplementedSLAMonitorServiceServer()
}

func RegisterSLAMonitorServiceServer(s grpc.ServiceRegistrar, srv SLAMonitorServiceServer) {
	// If the following call panics, it indicates UnimplementedSLAMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SLAMonitorService_ServiceDesc, srv)
}

func _SLAMonitorService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLAMonitorServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLAMonitorService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLAMonitorServiceServer).RecordEvent(ctx, req.(*RecordEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SLAMonitorService_GetSLAReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLAReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SLAMonitorServiceServer).GetSLAReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SLAMonitorService_GetSLAReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SLAMonitorServiceServer).GetSLAReport(ctx, req.(*GetSLAReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SLAMonitorService_ServiceDesc is the grpc.ServiceDesc for SLAMonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SLAMonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operations.SLAMonitorService",
	HandlerType: (*SLAMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEvent",
			Handler:    _SLAMonitorService_RecordEvent_Handler,
		},
		{
			MethodName: "GetSLAReport",
			Handler:    _SLAMonitorService_GetSLAReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operations.proto",
}
