version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: nimbusdb-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: nimbusdb-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: nimbusdb-jaeger
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC port
      - "4318:4318"   # OTLP HTTP port

  loki:
    image: grafana/loki:2.9.4
    container_name: nimbusdb-loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:10.3.3
    container_name: nimbusdb-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  webhook-receiver:
    build:
      context: ../../
      dockerfile: services/observability/webhook/Dockerfile
    container_name: nimbusdb-webhook-receiver
    ports:
      - "9099:9099"
